### PR TITLE
Add MIT License to the autoloader

### PR DESCRIPTION
**Pull request by diglin**
As provided by the original author of this class, please add the MIT license to prevent problem by using it.
Here is the original link to the gist of the author: https://gist.github.com/jwage/221634

### CODE REVIEW

**Comment by Flyingmana** [comment]
conflicts with the licence noted in composer.json

**Comment by diglin** [comment]
In composer you cannot set two licenses. how could it be resolved?  Removing the GPL license? or keeping the most constraining ?

**Comment by diglin** [comment]
Sorry I was wrong we can set multiple license: "licenses": ["MIT", "GPL"],

**Comment by Flyingmana** [comment]
btw. MIT is fine for me

**Pull request merged**
